#include <crails/odb/connection.hpp>
#include <crails/environment.hpp>
#include <crails/logger.hpp>
#include "../test_databases.hpp"
#include "test_record.hpp"
#include "test_record-odb.hpp" // generated by the odb compiler from test_record.hpp

#undef NODEBUG
#include <cassert>

void driver()
{
  using namespace Crails;
  using namespace std;

  Crails::environment = Crails::Test;
  SingletonInstantiator<TestDatabases> databases;
  create_test_schema();

  // BEGIN lazy transaction
  {
    Odb::Connection connection;

    assert(!connection.transaction().active());
  }

  // BEGIN commit-with-no-transaction-is-a-no-op
  {
    Odb::Connection connection;

    connection.commit();
    assert(!connection.transaction().active());
  }

  // BEGIN a plain Connection commits and persists
  {
    Odb::id_type id;

    {
      Odb::Connection connection;
      TestRecord      record("hello");

      connection.save(record);
      assert(connection.transaction().active());
      connection.commit();
      assert(!connection.transaction().active());
      id = record.get_id();
    }

    {
      Odb::Connection connection;
      shared_ptr<TestRecord> record;

      assert(connection.find_one(record, id));
      assert(record->get_label() == "hello");
    }
  }

  // BEGIN rollback_on_destruction: an uncommitted Connection rolls back
  {
    Odb::id_type id;

    {
      Odb::Connection connection;
      TestRecord      record("should not survive");

      connection.save(record);
      id = record.get_id();
    }

    {
      Odb::Connection connection;
      shared_ptr<TestRecord> record;

      assert(!connection.find_one(record, id));
    }
  }

  // BEGIN ConnectionHandle: standalone mode behaves like a plain Connection
  {
    Odb::ConnectionHandle handle;
    TestRecord            record("standalone handle");

    handle.save(record);
    assert(handle.transaction().active());
    handle.commit();

    Odb::Connection connection;
    shared_ptr<TestRecord> found;
    assert(connection.find_one(found, record.get_id()));
  }

  // BEGIN ConnectionHandle: proxy mode joins the target's transaction
  {
    Odb::Connection        target;
    TestRecord             record("proxied write");

    target.save(record);
    assert(target.transaction().active());

    {
      Odb::ConnectionHandle handle(target);
      shared_ptr<TestRecord> seen_through_handle;

      assert(handle.find_one(seen_through_handle, record.get_id()));
      assert(seen_through_handle->get_label() == "proxied write");
      // must NOT rollback transaction
    }

    assert(target.transaction().active());
    target.commit();

    Odb::Connection connection;
    shared_ptr<TestRecord> found;
    assert(connection.find_one(found, record.get_id()));
    assert(found->get_label() == "proxied write");
  }
}

int main()
{
  driver();
  Crails::logger.cleanup();
  return 0;
}
